import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const { Pool } = pg;
const app = express();
const PORT = Number(process.env.PORT || 10000);
const DATABASE_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET;
const ADMIN_KEY = process.env.ADMIN_KEY;
if (!DATABASE_URL) throw new Error('DATABASE_URL no está configurada.');
if (!JWT_SECRET) throw new Error('JWT_SECRET no está configurada.');
if (!ADMIN_KEY) throw new Error('ADMIN_KEY no está configurada.');
const pool = new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
app.set('trust proxy',1);
app.use(cors({origin:true,methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Admin-Key']}));
app.use(express.json({limit:'1mb'}));
app.use('/admin',express.static(new URL('./public',import.meta.url).pathname));
function cleanUsername(v){return String(v||'').trim().replace(/\s+/g,' ')}
function validUsername(v){return /^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9_. -]{3,30}$/.test(v)}
function validPassword(v){return typeof v==='string'&&v.length>=6&&v.length<=100}
function signToken(u){return jwt.sign({id:u.id,username:u.username},JWT_SECRET,{expiresIn:'30d'})}
function publicProfile(p,u){return {username:u,nombre:p?.nombre||u,avatar:p?.avatar||'',nivel:Number(p?.nivel)||1,xp:Number(p?.xp)||0,monedas:Number(p?.monedas)||0,habilidades:p?.habilidades&&typeof p.habilidades==='object'?p.habilidades:{pista:0,reintento:0,salto:0},progresoCursos:p?.progresoCursos||{},registrosGeneral:Array.isArray(p?.registrosGeneral)?p.registrosGeneral:[]}}
function parseProfile(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return{}}}
async function getUserById(id){const {rows}=await pool.query('SELECT id, username, profile_json, password_hash FROM users WHERE id=$1',[id]);if(!rows[0])return null;return {...rows[0],profile:parseProfile(rows[0].profile_json)}}
async function auth(req,res,next){const raw=String(req.headers.authorization||'');const token=raw.startsWith('Bearer ')?raw.slice(7):'';if(!token)return res.status(401).json({error:'Falta el token.'});try{const payload=jwt.verify(token,JWT_SECRET);const user=await getUserById(payload.id);if(!user)return res.status(401).json({error:'Cuenta no encontrada.'});req.user=user;next()}catch{return res.status(401).json({error:'Sesión inválida o expirada.'})}}
async function initDb(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);CREATE INDEX IF NOT EXISTS idx_users_updated_at ON users(updated_at DESC);`)}
app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'EduFriends',database:'postgres',time:new Date().toISOString()})}catch{res.status(503).json({ok:false,service:'EduFriends',database:'unavailable'})}});
app.post('/api/register',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=String(req.body?.password||''),profile=req.body?.profile&&typeof req.body.profile==='object'?req.body.profile:{};if(!validUsername(username))return res.status(400).json({error:'El usuario debe tener entre 3 y 30 caracteres.'});if(!validPassword(password))return res.status(400).json({error:'La contraseña debe tener al menos 6 caracteres.'});const exists=await pool.query('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[username]);if(exists.rows[0])return res.status(409).json({error:'Ese usuario ya existe. Usa Iniciar sesión.'});const hash=await bcrypt.hash(password,12),safeProfile=publicProfile(profile,username);const result=await pool.query('INSERT INTO users(username,password_hash,profile_json) VALUES($1,$2,$3::jsonb) RETURNING id,username,profile_json',[username,hash,JSON.stringify(safeProfile)]);const user={id:result.rows[0].id,username:result.rows[0].username,profile:parseProfile(result.rows[0].profile_json)};return res.status(201).json({token:signToken(user),profile:publicProfile(user.profile,user.username)})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo crear la cuenta.'})}});
app.post('/api/login',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=String(req.body?.password||'');const {rows}=await pool.query('SELECT id,username,password_hash,profile_json FROM users WHERE LOWER(username)=LOWER($1)',[username]);const row=rows[0];if(!row||!(await bcrypt.compare(password,row.password_hash)))return res.status(401).json({error:'Usuario o contraseña incorrectos.'});const user={id:row.id,username:row.username,profile:parseProfile(row.profile_json)};return res.json({token:signToken(user),profile:publicProfile(user.profile,user.username)})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo iniciar sesión.'})}});
app.get('/api/me',auth,async(req,res)=>{res.set('Cache-Control','no-store');res.json({profile:publicProfile(req.user.profile,req.user.username)})});
function isPlainObject(v){return v&&typeof v==='object'&&!Array.isArray(v)}
function resultValue(r){if(r===true)return true;if(r===false)return false;if(!isPlainObject(r))return null;if(r.correct===true||r.correcto===true||r.esCorrecta===true)return true;if(r.correct===false||r.correcto===false||r.esCorrecta===false)return false;const e=String(r.estado||r.resultado||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();if(['correcto','correcta'].includes(e))return true;if(['incorrecto','incorrecta','fallo','fallida'].includes(e))return false;return null}
function statsFromNode(node){if(!isPlainObject(node))return null;const candidates=[node.resultados,node.respuestas,node.answers,node.historial];for(const arr of candidates){if(!Array.isArray(arr))continue;const vals=arr.map(resultValue);const known=vals.filter(v=>v===true||v===false);if(known.length){return {answered:known.length,correct:known.filter(Boolean).length}}}const hasAnswered=node.respondidas!==undefined||node.respondidasTotal!==undefined||node.preguntasRespondidas!==undefined;const hasCorrect=node.correctas!==undefined||node.correctasTotal!==undefined||node.preguntasCorrectas!==undefined;if(hasAnswered||hasCorrect){const answered=Math.max(0,Number(node.respondidas??node.respondidasTotal??node.preguntasRespondidas)||0);const correct=Math.max(0,Math.min(answered,Number(node.correctas??node.correctasTotal??node.preguntasCorrectas)||0));return {answered,correct}}return null}
function aggregateCourseNode(node){const direct=statsFromNode(node);if(direct)return direct;let answered=0,correct=0;if(isPlainObject(node)){for(const [key,value] of Object.entries(node)){if(['preguntaActual','indice','nivel'].includes(key))continue;const s=aggregateCourseNode(value);answered+=s.answered;correct+=s.correct}}return {answered,correct}}
function normalizeCourse(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function courseMatches(v,c){const a=normalizeCourse(v),b=normalizeCourse(c);if(!a||!b)return false;return a===b||a.startsWith(b+' (')||a.startsWith(b+'|')||a.startsWith(b+' -')||a.startsWith(b+' —')||a.startsWith(b+' /')}
function rankingForCourse(course,users){const ranking=[];for(const row of users){const p=parseProfile(row.profile_json);const progreso=isPlainObject(p.progresoCursos)?p.progresoCursos:{};let answered=0,correct=0,matched=false;for(const [key,node] of Object.entries(progreso)){if(!courseMatches(key,course))continue;matched=true;const s=aggregateCourseNode(node);answered+=s.answered;correct+=s.correct}if(!matched||correct===0){const regs=Array.isArray(p.registrosGeneral)?p.registrosGeneral:[];for(const r of regs){const courseName=r?.cursoNivel??r?.curso??r?.cursoNombre;if(courseMatches(courseName,course)){const rv=resultValue(r);if(rv===true){answered++;correct++}else if(rv===false){answered++}}}}if(correct<1)continue;ranking.push({username:row.username,nombre:p.nombre||row.username,avatar:p.avatar||'',nivel:Number(p.nivel)||1,xp:Number(p.xp)||0,correctas:correct,respondidas:answered})}ranking.sort((a,b)=>b.correctas-a.correctas||b.respondidas-a.respondidas||b.xp-a.xp||a.username.localeCompare(b.username));return ranking.slice(0,50).map((x,i)=>({posicion:i+1,...x}))}
app.put('/api/me',auth,async(req,res)=>{try{const incoming=req.body?.profile;if(!isPlainObject(incoming))return res.status(400).json({error:'Perfil inválido.'});const oldP=isPlainObject(req.user.profile)?req.user.profile:{};const incomingCourses=isPlainObject(incoming.progresoCursos)?incoming.progresoCursos:{};const oldCourses=isPlainObject(oldP.progresoCursos)?oldP.progresoCursos:{};const mergedCourses={...oldCourses,...incomingCourses};for(const [courseKey,incomingCourse] of Object.entries(incomingCourses)){const oldCourse=oldCourses[courseKey];if(!isPlainObject(incomingCourse)){continue}if(!isPlainObject(oldCourse)){mergedCourses[courseKey]=incomingCourse;continue}const mergedCourse={...oldCourse,...incomingCourse};for(const [levelKey,incomingLevel] of Object.entries(incomingCourse)){const oldLevel=oldCourse[levelKey];if(isPlainObject(incomingLevel)&&isPlainObject(oldLevel)){const mergedLevel={...oldLevel,...incomingLevel};const oldResults=Array.isArray(oldLevel.resultados)?oldLevel.resultados:[];const newResults=Array.isArray(incomingLevel.resultados)?incomingLevel.resultados:[];if(oldResults.length||newResults.length){const len=Math.max(oldResults.length,newResults.length);mergedLevel.resultados=Array.from({length:len},(_,i)=>{const n=newResults[i];return n===true||n===false?n:oldResults[i]})}mergedLevel.respondidas=Math.max(Number(oldLevel.respondidas)||0,Number(incomingLevel.respondidas)||0);mergedLevel.correctas=Math.max(Number(oldLevel.correctas)||0,Number(incomingLevel.correctas)||0);mergedCourse[levelKey]=mergedLevel}}mergedCourses[courseKey]=mergedCourse}
const profile=publicProfile({...oldP,...incoming,progresoCursos:mergedCourses},req.user.username);const oldRegs=Array.isArray(oldP.registrosGeneral)?oldP.registrosGeneral:[];const newRegs=Array.isArray(incoming.registrosGeneral)?incoming.registrosGeneral:[];profile.registrosGeneral=newRegs.length>=oldRegs.length?newRegs:oldRegs;await pool.query('UPDATE users SET profile_json=$1::jsonb,updated_at=NOW() WHERE id=$2',[JSON.stringify(profile),req.user.id]);req.user.profile=profile;return res.json({ok:true,profile})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo guardar el progreso.'})}});
async function deleteAuthenticatedAccount(req,res){try{const result=await pool.query('DELETE FROM users WHERE id=$1 RETURNING id,username');if(!result.rows[0])return res.status(404).json({error:'Cuenta no encontrada.'});res.set('Cache-Control','no-store');return res.json({ok:true,deleted:true,username:result.rows[0].username,message:'Cuenta y todos sus datos eliminados correctamente.'})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo eliminar la cuenta.'})}}
app.delete('/api/me',auth,deleteAuthenticatedAccount);app.post('/api/delete-account',auth,deleteAuthenticatedAccount);
app.get('/api/rankings',async(req,res)=>{try{const course=cleanUsername(req.query.course);if(!course)return res.status(400).json({error:'Falta course.'});const {rows}=await pool.query('SELECT username,profile_json FROM users');const ranking=rankingForCourse(course,rows);res.set('Cache-Control','no-store');res.json({ok:true,course,totalUsuarios:ranking.length,ranking})}catch(e){console.error(e);res.status(500).json({error:'No se pudo cargar el ranking.'})}});
app.post('/api/admin/limpiar-todo',async(req,res)=>{try{if(String(req.headers['x-admin-key']||'')!==ADMIN_KEY)return res.status(403).json({error:'No autorizado.'});const result=await pool.query('DELETE FROM users');res.json({ok:true,mensaje:'Todas las cuentas y sus progresos fueron eliminados.',eliminados:result.rowCount})}catch(e){console.error(e);res.status(500).json({error:'No se pudieron eliminar las cuentas.'})}});
app.get('/api/admin/users',async(req,res)=>{try{if(String(req.headers['x-admin-key']||'')!==ADMIN_KEY)return res.status(403).json({error:'No se pudo cargar la lista de usuarios.'});const {rows}=await pool.query('SELECT id,username,profile_json,created_at,updated_at FROM users ORDER BY updated_at DESC');res.json({users:rows.map(r=>({id:r.id,username:r.username,profile:parseProfile(r.profile_json),created_at:r.created_at,updated_at:r.updated_at}))})}catch(e){console.error(e);res.status(500).json({error:'No se pudo cargar la lista de usuarios.'})}});
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Error interno del servidor.'})});
await initDb();app.listen(PORT,'0.0.0.0',()=>console.log(`EduFriends server listening on 0.0.0.0:${PORT}`));