import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const { Pool } = pg;
const app = express();
const PORT = Number(process.env.PORT || 10000);
const DATABASE_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET;
const ADMIN_KEY = process.env.ADMIN_KEY;
if (!DATABASE_URL) throw new Error('DATABASE_URL no está configurada.');
if (!JWT_SECRET) throw new Error('JWT_SECRET no está configurada.');
if (!ADMIN_KEY) throw new Error('ADMIN_KEY no está configurada.');
const pool = new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
app.set('trust proxy',1);
app.use(cors({origin:true,methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Admin-Key']}));
app.use(express.json({limit:'2mb'}));
app.use('/admin',express.static(new URL('./public',import.meta.url).pathname));
function cleanUsername(v){return String(v??'').trim().replace(/\s+/g,' ')}
function validUsername(v){return /^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9_. -]{3,30}$/.test(v)}
function validPassword(v){return typeof v==='string'&&v.length>=6&&v.length<=100}
function signToken(u){return jwt.sign({id:u.id,username:u.username},JWT_SECRET,{expiresIn:'30d'})}
function isObj(v){return v&&typeof v==='object'&&!Array.isArray(v)}
function parseProfile(v){if(isObj(v))return v;try{return JSON.parse(v||'{}')}catch{return{}}}
function publicProfile(p,u){return {username:u,nombre:p?.nombre||u,avatar:p?.avatar||'',nivel:Number(p?.nivel)||1,xp:Number(p?.xp)||0,monedas:Number(p?.monedas)||0,habilidades:isObj(p?.habilidades)?p.habilidades:{pista:0,reintento:0,salto:0},progresoCursos:isObj(p?.progresoCursos)?p.progresoCursos:{},registrosGeneral:Array.isArray(p?.registrosGeneral)?p.registrosGeneral:[]}}
async function getUserById(id){const {rows}=await pool.query('SELECT id,username,profile_json,password_hash FROM users WHERE id=$1',[id]);if(!rows[0])return null;return {...rows[0],profile:parseProfile(rows[0].profile_json)}}
async function auth(req,res,next){const raw=String(req.headers.authorization||'');const token=raw.startsWith('Bearer ')?raw.slice(7):'';if(!token)return res.status(401).json({error:'Falta el token.'});try{const payload=jwt.verify(token,JWT_SECRET);const user=await getUserById(payload.id);if(!user)return res.status(401).json({error:'Cuenta no encontrada.'});req.user=user;next()}catch{return res.status(401).json({error:'Sesión inválida o expirada.'})}}
async function initDb(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);CREATE INDEX IF NOT EXISTS idx_users_updated_at ON users(updated_at DESC);`)}
app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.set('Cache-Control','no-store');res.json({ok:true,service:'EduFriends',database:'postgres',time:new Date().toISOString()})}catch(e){console.error(e);res.status(503).json({ok:false,service:'EduFriends',database:'unavailable'})}});
app.post('/api/register',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=String(req.body?.password||''),profile=isObj(req.body?.profile)?req.body.profile:{};if(!validUsername(username))return res.status(400).json({error:'El usuario debe tener entre 3 y 30 caracteres.'});if(!validPassword(password))return res.status(400).json({error:'La contraseña debe tener al menos 6 caracteres.'});const exists=await pool.query('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[username]);if(exists.rows[0])return res.status(409).json({error:'Ese usuario ya existe. Usa Iniciar sesión.'});const hash=await bcrypt.hash(password,12);const safe=publicProfile(profile,username);const r=await pool.query('INSERT INTO users(username,password_hash,profile_json) VALUES($1,$2,$3::jsonb) RETURNING id,username,profile_json',[username,hash,JSON.stringify(safe)]);const user={id:r.rows[0].id,username:r.rows[0].username,profile:parseProfile(r.rows[0].profile_json)};res.status(201).json({token:signToken(user),profile:publicProfile(user.profile,user.username)})}catch(e){console.error(e);res.status(500).json({error:'No se pudo crear la cuenta.'})}});
app.post('/api/login',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=String(req.body?.password||'');const {rows}=await pool.query('SELECT id,username,password_hash,profile_json FROM users WHERE LOWER(username)=LOWER($1)',[username]);const row=rows[0];if(!row||!(await bcrypt.compare(password,row.password_hash)))return res.status(401).json({error:'Usuario o contraseña incorrectos.'});const user={id:row.id,username:row.username,profile:parseProfile(row.profile_json)};res.set('Cache-Control','no-store');res.json({token:signToken(user),profile:publicProfile(user.profile,user.username)})}catch(e){console.error(e);res.status(500).json({error:'No se pudo iniciar sesión.'})}});
app.get('/api/me',auth,(req,res)=>{res.set('Cache-Control','no-store');res.json({profile:publicProfile(req.user.profile,req.user.username)})});
function resultValue(v){if(v===true||v===false)return v;if(!isObj(v))return null;if(v.correct===true||v.correcto===true||v.esCorrecta===true)return true;if(v.correct===false||v.correcto===false||v.esCorrecta===false)return false;const s=String(v.estado??v.resultado??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();if(s==='correcto'||s==='correcta')return true;if(['incorrecto','incorrecta','fallo','fallida'].includes(s))return false;return null}
function countNode(node){if(!isObj(node))return {answered:0,correct:0};let answered=0,correct=0;for(const key of ['resultados','respuestas','answers','historial']){const arr=node[key];if(!Array.isArray(arr))continue;const vals=arr.map(resultValue).filter(v=>v===true||v===false);if(vals.length){answered=Math.max(answered,vals.length);correct=Math.max(correct,vals.filter(Boolean).length)}}const explicit=Number(node.respondidas??node.respondidasTotal??node.preguntasRespondidas);const explicitCorrect=Number(node.correctas??node.correctasTotal??node.preguntasCorrectas);if(Number.isFinite(explicit)&&explicit>=0)answered=Math.max(answered,explicit);if(Number.isFinite(explicitCorrect)&&explicitCorrect>=0)correct=Math.max(correct,explicitCorrect);return {answered:Math.max(answered,correct),correct:Math.min(correct,Math.max(answered,correct))}}
function aggregate(node){const direct=countNode(node);if(direct.answered||direct.correct)return direct;if(!isObj(node))return direct;let a=0,c=0;for(const [k,v] of Object.entries(node)){if(['preguntaActual','indice','nivel','nombre'].includes(k))continue;const s=aggregate(v);a+=s.answered;c+=s.correct}return{answered:a,correct:c}}
function normalizeCourse(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function courseMatches(v,c){const a=normalizeCourse(v),b=normalizeCourse(c);return !!a&&!!b&&(a===b||a.startsWith(b+' (')||a.startsWith(b+'|')||a.startsWith(b+' -')||a.startsWith(b+' —')||a.startsWith(b+' /'))}
function rankingForCourse(course,users){const ranking=[];for(const row of users){const p=parseProfile(row.profile_json);const courses=isObj(p.progresoCursos)?p.progresoCursos:{};let answered=0,correct=0,matched=false;for(const [key,node] of Object.entries(courses)){if(!courseMatches(key,course))continue;matched=true;const s=aggregate(node);answered+=s.answered;correct+=s.correct}if(!matched||answered===0){const regs=Array.isArray(p.registrosGeneral)?p.registrosGeneral:[];for(const r of regs){const n=r?.cursoNivel??r?.curso??r?.cursoNombre;if(!courseMatches(n,course))continue;const rv=resultValue(r);if(rv!==null){answered++;if(rv)correct++}}}if(correct<1)continue;ranking.push({username:row.username,nombre:p.nombre||row.username,avatar:p.avatar||'',nivel:Number(p.nivel)||1,xp:Number(p.xp)||0,correctas:correct,respondidas:answered,incorrectas:Math.max(0,answered-correct)})}ranking.sort((a,b)=>b.correctas-a.correctas||b.respondidas-a.respondidas||b.xp-a.xp||a.username.localeCompare(b.username));return ranking.slice(0,50).map((x,i)=>({posicion:i+1,...x}))}
function mergeResultArrays(oldArr,newArr){const a=Array.isArray(oldArr)?oldArr:[],b=Array.isArray(newArr)?newArr:[];const len=Math.max(a.length,b.length);return Array.from({length:len},(_,i)=>{const n=b[i],o=a[i];return n===true||n===false?n:o})}
function mergeLevel(oldL,newL){if(!isObj(oldL))return newL;if(!isObj(newL))return oldL;const out={...oldL,...newL};const r=mergeResultArrays(oldL.resultados,newL.resultados);if(r.length)out.resultados=r;out.respondidas=Math.max(Number(oldL.respondidas)||0,Number(newL.respondidas)||0);out.correctas=Math.max(Number(oldL.correctas)||0,Number(newL.correctas)||0);return out}
function mergeProfiles(oldP,incoming,username){const out={...oldP,...incoming};const oldC=isObj(oldP.progresoCursos)?oldP.progresoCursos:{};const newC=isObj(incoming.progresoCursos)?incoming.progresoCursos:{};const courses={...oldC};for(const [k,v] of Object.entries(newC))courses[k]=mergeLevel(oldC[k],v);out.progresoCursos=courses;const oldR=Array.isArray(oldP.registrosGeneral)?oldP.registrosGeneral:[];const newR=Array.isArray(incoming.registrosGeneral)?incoming.registrosGeneral:[];out.registrosGeneral=newR.length>=oldR.length?newR:oldR;return publicProfile(out,username)}
app.put('/api/me',auth,async(req,res)=>{try{if(!isObj(req.body?.profile))return res.status(400).json({error:'Perfil inválido.'});const profile=mergeProfiles(req.user.profile,req.body.profile,req.user.username);await pool.query('UPDATE users SET profile_json=$1::jsonb,updated_at=NOW() WHERE id=$2',[JSON.stringify(profile),req.user.id]);req.user.profile=profile;res.set('Cache-Control','no-store');res.json({ok:true,profile})}catch(e){console.error(e);res.status(500).json({error:'No se pudo guardar el progreso.'})}});
async function deleteAuthenticatedAccount(req,res){try{const r=await pool.query('DELETE FROM users WHERE id=$1 RETURNING username',[req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Cuenta no encontrada.'});res.set('Cache-Control','no-store');res.json({ok:true,deleted:true,username:r.rows[0].username,message:'Cuenta y todos sus datos eliminados correctamente.'})}catch(e){console.error(e);res.status(500).json({error:'No se pudo eliminar la cuenta.'})}}
app.delete('/api/me',auth,deleteAuthenticatedAccount);app.post('/api/delete-account',auth,deleteAuthenticatedAccount);
app.get('/api/rankings',async(req,res)=>{try{const course=cleanUsername(req.query.course);if(!course)return res.status(400).json({error:'Falta course.'});const {rows}=await pool.query('SELECT username,profile_json FROM users');const ranking=rankingForCourse(course,rows);res.set('Cache-Control','no-store');res.json({ok:true,course,totalUsuarios:ranking.length,ranking})}catch(e){console.error(e);res.status(500).json({error:'No se pudo cargar el ranking.'})}});
app.post('/api/admin/limpiar-todo',async(req,res)=>{try{if(String(req.headers['x-admin-key']||'')!==ADMIN_KEY)return res.status(403).json({error:'No autorizado.'});const r=await pool.query('DELETE FROM users');res.json({ok:true,mensaje:'Todas las cuentas y sus progresos fueron eliminados.',eliminados:r.rowCount})}catch(e){console.error(e);res.status(500).json({error:'No se pudieron eliminar las cuentas.'})}});
app.get('/api/admin/users',async(req,res)=>{try{if(String(req.headers['x-admin-key']||'')!==ADMIN_KEY)return res.status(403).json({error:'No autorizado.'});const {rows}=await pool.query('SELECT id,username,profile_json,created_at,updated_at FROM users ORDER BY updated_at DESC');res.json({users:rows.map(r=>({id:r.id,username:r.username,profile:parseProfile(r.profile_json),created_at:r.created_at,updated_at:r.updated_at}))})}catch(e){console.error(e);res.status(500).json({error:'No se pudo cargar la lista de usuarios.'})}});
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Error interno del servidor.'})});
await initDb();app.listen(PORT,'0.0.0.0',()=>console.log(`EduFriends server listening on 0.0.0.0:${PORT}`));