import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const { Pool } = pg;
const app = express();
const PORT = Number(process.env.PORT || 10000);
const DATABASE_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET;
const ADMIN_KEY = process.env.ADMIN_KEY;
if (!DATABASE_URL) throw new Error('DATABASE_URL no está configurada.');
if (!JWT_SECRET) throw new Error('JWT_SECRET no está configurada.');
if (!ADMIN_KEY) throw new Error('ADMIN_KEY no está configurada.');
const pool = new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
app.set('trust proxy',1);
app.use(cors({origin:true,methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Admin-Key']}));
app.use(express.json({limit:'1mb'}));
app.use('/admin',express.static(new URL('./public',import.meta.url).pathname));
function cleanUsername(v){return String(v||'').trim().replace(/\s+/g,' ')}
function validUsername(v){return /^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9_. -]{3,30}$/.test(v)}
function validPassword(v){return typeof v==='string'&&v.length>=6&&v.length<=100}
function signToken(u){return jwt.sign({id:u.id,username:u.username},JWT_SECRET,{expiresIn:'30d'})}
function publicProfile(p,u){return {username:u,nombre:p?.nombre||u,avatar:p?.avatar||'',nivel:Number(p?.nivel)||1,xp:Number(p?.xp)||0,monedas:Number(p?.monedas)||0,habilidades:p?.habilidades&&typeof p.habilidades==='object'?p.habilidades:{pista:0,reintento:0,salto:0},progresoCursos:p?.progresoCursos||{},registrosGeneral:Array.isArray(p?.registrosGeneral)?p.registrosGeneral:[]}}
function parseProfile(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return{}}}
async function getUserById(id){const {rows}=await pool.query('SELECT id, username, profile_json, password_hash FROM users WHERE id=$1',[id]);if(!rows[0])return null;return {...rows[0],profile:parseProfile(rows[0].profile_json)}}
async function auth(req,res,next){const raw=String(req.headers.authorization||'');const token=raw.startsWith('Bearer ')?raw.slice(7):'';if(!token)return res.status(401).json({error:'Falta el token.'});try{const payload=jwt.verify(token,JWT_SECRET);const user=await getUserById(payload.id);if(!user)return res.status(401).json({error:'Cuenta no encontrada.'});req.user=user;next()}catch{return res.status(401).json({error:'Sesión inválida o expirada.'})}}
async function initDb(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);CREATE INDEX IF NOT EXISTS idx_users_updated_at ON users(updated_at DESC);`)}
app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'EduFriends',database:'postgres',time:new Date().toISOString()})}catch{res.status(503).json({ok:false,service:'EduFriends',database:'unavailable'})}});
app.post('/api/register',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=String(req.body?.password||''),profile=req.body?.profile&&typeof req.body.profile==='object'?req.body.profile:{};if(!validUsername(username))return res.status(400).json({error:'El usuario debe tener entre 3 y 30 caracteres.'});if(!validPassword(password))return res.status(400).json({error:'La contraseña debe tener al menos 6 caracteres.'});const exists=await pool.query('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[username]);if(exists.rows[0])return res.status(409).json({error:'Ese usuario ya existe. Usa Iniciar sesión.'});const hash=await bcrypt.hash(password,12),safeProfile=publicProfile(profile,username);const result=await pool.query('INSERT INTO users(username,password_hash,profile_json) VALUES($1,$2,$3::jsonb) RETURNING id,username,profile_json',[username,hash,JSON.stringify(safeProfile)]);const user={id:result.rows[0].id,username:result.rows[0].username,profile:parseProfile(result.rows[0].profile_json)};return res.status(201).json({token:signToken(user),profile:publicProfile(user.profile,user.username)})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo crear la cuenta.'})}});
app.post('/api/login',async(req,res)=>{try{const username=cleanUsername(req.body?.username),password=String(req.body?.password||'');const {rows}=await pool.query('SELECT id,username,password_hash,profile_json FROM users WHERE LOWER(username)=LOWER($1)',[username]);const row=rows[0];if(!row||!(await bcrypt.compare(password,row.password_hash)))return res.status(401).json({error:'Usuario o contraseña incorrectos.'});const user={id:row.id,username:row.username,profile:parseProfile(row.profile_json)};return res.json({token:signToken(user),profile:publicProfile(user.profile,user.username)})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo iniciar sesión.'})}});
app.get('/api/me',auth,(req,res)=>{res.set('Cache-Control','no-store');res.json({profile:publicProfile(req.user.profile,req.user.username)})});
function mergeProgressItem(existing,incoming){const oldItem=existing&&typeof existing==='object'?existing:{};const newItem=incoming&&typeof incoming==='object'?incoming:{};const merged={...oldItem,...newItem};const oldResults=Array.isArray(oldItem.resultados)?oldItem.resultados:[];const newResults=Array.isArray(newItem.resultados)?newItem.resultados:[];if(oldResults.length||newResults.length){const len=Math.max(oldResults.length,newResults.length);merged.resultados=Array.from({length:len},(_,i)=>{const nv=newResults[i];return(nv===true||nv===false)?nv:(oldResults[i]===true||oldResults[i]===false?oldResults[i]:nv)});}merged.respondidas=Math.max(Number(oldItem.respondidas)||0,Number(newItem.respondidas)||0);if(newItem.completado===undefined&&oldItem.completado!==undefined)merged.completado=oldItem.completado;return merged}
function mergeProgressTree(existing,incoming){const oldObj=existing&&typeof existing==='object'?existing:{};const newObj=incoming&&typeof incoming==='object'?incoming:{};const out={...oldObj,...newObj};for(const key of Object.keys(newObj)){const nv=newObj[key],ov=oldObj[key];if(nv&&typeof nv==='object'&&!Array.isArray(nv)&&ov&&typeof ov==='object'&&!Array.isArray(ov))out[key]=mergeProgressTree(ov,nv);else if(nv&&typeof nv==='object'&&!Array.isArray(nv))out[key]=mergeProgressTree({},nv)}return out}
function mergeProfilesForSave(existing,incoming,username){const oldP=existing&&typeof existing==='object'?existing:{};const newP=incoming&&typeof incoming==='object'?incoming:{};const profile=publicProfile(newP,username);profile.progresoCursos=mergeProgressTree(oldP.progresoCursos,newP.progresoCursos);const oldRegs=Array.isArray(oldP.registrosGeneral)?oldP.registrosGeneral:[];const newRegs=Array.isArray(newP.registrosGeneral)?newP.registrosGeneral:[];profile.registrosGeneral=newRegs.length>=oldRegs.length?newRegs:oldRegs;return profile}
app.put('/api/me',auth,async(req,res)=>{try{const incoming=req.body?.profile;if(!incoming||typeof incoming!=='object')return res.status(400).json({error:'Perfil inválido.'});const profile=mergeProfilesForSave(req.user.profile,incoming,req.user.username);await pool.query('UPDATE users SET profile_json=$1::jsonb,updated_at=NOW() WHERE id=$2',[JSON.stringify(profile),req.user.id]);req.user.profile=profile;return res.json({ok:true,profile})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo guardar el progreso.'})}});
async function deleteAuthenticatedAccount(req,res){try{const result=await pool.query('DELETE FROM users WHERE id=$1 RETURNING id,username',[req.user.id]);if(!result.rows[0])return res.status(404).json({error:'Cuenta no encontrada.'});res.set('Cache-Control','no-store');return res.json({ok:true,deleted:true,username:result.rows[0].username,message:'Cuenta y todos sus datos eliminados correctamente.'})}catch(e){console.error(e);return res.status(500).json({error:'No se pudo eliminar la cuenta.'})}}
app.delete('/api/me',auth,deleteAuthenticatedAccount);app.post('/api/delete-account',auth,deleteAuthenticatedAccount);
function normalizeCourse(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function courseMatches(v,c){const a=normalizeCourse(v),b=normalizeCourse(c);if(!a||!b)return false;return a===b||a.startsWith(b+' (')||a.startsWith(b+'|')||a.startsWith(b+' -')||a.startsWith(b+' —')||a.startsWith(b+' /')}
function resultValue(r){if(r===true)return true;if(r===false)return false;if(!r||typeof r!=='object')return null;if(r.correct===true||r.correcto===true||r.esCorrecta===true)return true;if(r.correct===false||r.correcto===false||r.esCorrecta===false)return false;const e=normalizeCourse(r.estado||r.resultado||'');if(e==='correcto'||e==='correcta')return true;if(e==='incorrecto'||e==='incorrecta'||e==='fallo'||e==='fallida')return false;return null}
function directStats(item){if(!item||typeof item!=='object'||Array.isArray(item))return null;const arrays=[item.resultados,item.respuestas,item.answers,item.historial].filter(Array.isArray);let values=[];for(const arr of arrays){const parsed=arr.map(resultValue).filter(v=>v===true||v===false);if(parsed.length){values=parsed;break}}const explicitAnswered=Number(item.respondidas??item.respondidasTotal??item.preguntasRespondidas);const explicitCorrect=Number(item.correctas??item.correctasTotal??item.preguntasCorrectas);if(values.length||Number.isFinite(explicitAnswered)||Number.isFinite(explicitCorrect)){const answered=Number.isFinite(explicitAnswered)&&explicitAnswered>=0?explicitAnswered:values.length;const correct=values.length?values.filter(Boolean).length:(Number.isFinite(explicitCorrect)?explicitCorrect:0);return{answered:Math.max(0,answered),correct:Math.max(0,Math.min(correct,answered))}}return null}
function aggregateStats(item){const direct=directStats(item);if(direct)return direct;let answered=0,correct=0;if(item&&typeof item==='object'&&!Array.isArray(item)){for(const [k,v] of Object.entries(item)){if(k==='preguntaActual'||k==='pregunta'||k==='indice'||k==='nivel')continue;const s=aggregateStats(v);answered+=s.answered;correct+=s.correct}}return{answered,correct}}
function buildRankingEntry(row,p,c,a){return{username:row.username,nombre:p.nombre||row.username,avatar:p.avatar||'',nivel:Number(p.nivel)||1,xp:Number(p.xp)||0,correctas:c,respondidas:a}}
function rankingForCourse(course,users){const ranking=[];for(const row of users){const p=parseProfile(row.profile_json);const progreso=p.progresoCursos&&typeof p.progresoCursos==='object'?p.progresoCursos:{};let progressAnswered=0,progressCorrect=0,matched=false;for(const key of Object.keys(progreso)){if(!courseMatches(key,course))continue;matched=true;const s=aggregateStats(progreso[key]);progressAnswered+=s.answered;progressCorrect+=s.correct}let correct=progressCorrect,answered=progressAnswered;if(!matched||answered===0){const registros=Array.isArray(p.registrosGeneral)?p.registrosGeneral:[];const regs=registros.filter(r=>(courseMatches(r?.cursoNivel,course)||courseMatches(r?.curso,course)||courseMatches(r?.cursoNombre,course))&&(resultValue(r)===true||resultValue(r)===false));if(regs.length){answered=regs.length;correct=regs.reduce((n,r)=>n+(resultValue(r)===true?1:0),0)}}if(answered<1)continue;ranking.push(buildRankingEntry(row,p,correct,answered))}ranking.sort((a,b)=>b.correctas-a.correctas||b.respondidas-a.respondidas||b.xp-a.xp||a.username.localeCompare(b.username));return ranking.slice(0,50).map((x,i)=>({posicion:i+1,...x}))}
app.get('/api/rankings',async(req,res)=>{try{const course=cleanUsername(req.query.course);if(!course)return res.status(400).json({error:'Falta course.'});const {rows}=await pool.query('SELECT username,profile_json FROM users');const ranking=rankingForCourse(course,rows);res.set('Cache-Control','no-store');res.json({ok:true,course,totalUsuarios:ranking.length,ranking})}catch(e){console.error(e);res.status(500).json({error:'No se pudo cargar el ranking.'})}});
app.post('/api/admin/limpiar-todo',async(req,res)=>{try{if(String(req.headers['x-admin-key']||'')!==ADMIN_KEY)return res.status(403).json({error:'No autorizado.'});const result=await pool.query('DELETE FROM users');res.json({ok:true,mensaje:'Todas las cuentas y sus progresos fueron eliminados.',eliminados:result.rowCount})}catch(e){console.error(e);res.status(500).json({error:'No se pudieron eliminar las cuentas.'})}});
app.get('/api/admin/users',async(req,res)=>{try{if(String(req.headers['x-admin-key']||'')!==ADMIN_KEY)return res.status(403).json({error:'No se pudo cargar la lista de usuarios.'});const {rows}=await pool.query('SELECT id,username,profile_json,created_at,updated_at FROM users ORDER BY updated_at DESC');res.json({users:rows.map(r=>({id:r.id,username:r.username,profile:parseProfile(r.profile_json),created_at:r.created_at,updated_at:r.updated_at}))})}catch(e){console.error(e);res.status(500).json({error:'No se pudo cargar la lista de usuarios.'})}});
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Error interno del servidor.'})});
await initDb();app.listen(PORT,'0.0.0.0',()=>console.log(`EduFriends server listening on 0.0.0.0:${PORT}`));